### ISSUE TITLE
Init Project

### ISSUE THREAD

**Issue by foxprogs** [glokascom/bibleVis#1]
Нужно установить NextJS с app routing

**Comment by DenisArger** [comment]
yarn create next-app biblevis 

√ Would you like to use TypeScript? ... **No** / Yes
√ Would you like to use ESLint? ... No / **Yes**
√ Would you like to use Tailwind CSS? ... No / **Yes**
√ Would you like to use `src/` directory? ... **No** / Yes
√ Would you like to use App Router? (recommended) ... No / **Yes**
√ Would you like to customize the default import alias (@/*)? ... **No** / Yes
