### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by Valyukhov** [glokascom/bibleVis#13]
Настроить i18next для локализации.
Основной и пока единственный язык - en.

**Comment by DenisArger** [comment]
Буду действовать по этой инструкции:
https://github.com/i18next/next-i18next

**Comment by DenisArger** [comment]
**Цель**: добавить поддержку локализации с использованием i18next.
**Критерий выполнения:** подгружается перевод из common.json

**Comment by DenisArger** [comment]
Порядок действий:
1. Создать необходимую структуру папок (динамический сегмент):

![Image](https://github.com/user-attachments/assets/32e6a793-fddb-49c2-99af-9c43a0d3f458)


2. Создать файл app/i18n/settings.js
3. Внести правки app/[lng]/layout.js
4. Создать файл middleware.js
5. Установить accept-language
6. Подготовить файл app/i18n/index.js
7. Подготовить файл app/i18n/settings.js
8. Подготовить файл с локализацией (common.js)
9. Внедрить использование локализации на конкретной странице
- import { useTranslation } from '../i18n'
-  const { t } = useTranslation(lng)

**Comment by foxprogs** [comment]
@DenisArger вроде все отлично

**Comment by DenisArger** [comment]
> @DenisArger вроде все отлично

@foxprogs спасибо, буду действовать

**Comment by Valyukhov** [comment]
Да, хорошо.
Если что,есть примеры в комьюнити чек, там же тоже app router

**Comment by DenisArger** [comment]
> Да, хорошо. Если что,есть примеры в комьюнити чек, там же тоже app router
@Valyukhov отлично, спасибо тебе!
