### ISSUE TITLE
[Design]:Different loading design

### ISSUE THREAD

**Issue by Valyukhov** [glokascom/bibleVis#141]
### Task description:

Везде используем разный дизайн кнопок при загрузке.
![Image](https://github.com/user-attachments/assets/e314d3c6-b7b0-44f3-a8ca-b3fbb09974fa)
![Image](https://github.com/user-attachments/assets/e88e6b79-5963-4d62-bc24-955ee0916d6b)

![Image](https://github.com/user-attachments/assets/95cd343f-e5b7-4f96-ab5c-fe601c14ace0)

нужно создать один и его придерживаться

**Comment by Vlad-Syakov** [comment]
https://codepen.io/BridgetCReed/pen/YpOEVv
![Image](https://github.com/user-attachments/assets/c06427f6-9a23-4130-afee-62e3a939c4d2)

**Comment by Pavel064** [comment]
Влад, пожалуйста, расписывай подробнее решение задачи, вот прям как детям))

Например, нам будет понятнее, если так напишешь в этом случае: 

- Нашёл пример кода по ссылке https://codepen.io/BridgetCReed/pen/YpOEVv
- выбрал вариант (![image](https://github.com/user-attachments/assets/02e7c868-0789-4db6-8aaf-a8cd36ef508b))
- готовое решение, которое будем использовать уже в фигме (https://www.figma.com/design/aAEsApaCTnTut2sSgLa6G3/BibleVis-GeCraft?node-id=3091-1884&t=J2jxQfM18ynE5ENa-1)
- скриншот готового решения 
![{E57F9E2F-4433-4E58-A66E-8928E558EBA6}](https://github.com/user-attachments/assets/022923f2-9cd2-40bb-beba-919c480805a0)
