### ISSUE TITLE
[Feature]: Testing

### ISSUE THREAD

**Issue by foxprogs** [glokascom/bibleVis#21]
### Task description:

Настроить проект так, чтобы можно было писать юнит тесты и e2e тесты. 

### Examples and links:

[Основная документация по тестированию](https://nextjs.org/docs/app/building-your-application/testing)
[Vitest](https://nextjs.org/docs/app/building-your-application/testing/vitest)
[Playwright](https://nextjs.org/docs/app/building-your-application/testing/playwright)

### Evaluation criteria:
1. Для тестирования нам надо чтобы на проекте было настроено playwright (для асинхронных компонентов) и vitest (для обычных компонентов)
2. Если написать в консоли yarn test то должны запуститься 2 вида тестов и вернуть pass
3. Если написать yarn test:unit то должны запуститься только юнит тесты, там будет только один тест который проверяет компонент кнопки. Для этого надо создать еще одну страницу или компонент
4. Если написать yarn test:e2e то запустится e2e тесты, там будет один тест который проверяет async страницу, что на странице есть default кнопка
5. Структура папок будет такая же, как в документации nextjs

### Implementation steps:
1.
2.

**Comment by DenisArger** [comment]
Задача разбивается на две подзадачи:
1. Настройка playwright 
2. Настройка vitest  или Jest


 Настройка playwright (https://playwright.dev/docs/intro#installation)
1. Установка playwright : `yarn create playwright`
2. Выполнить следующие настройки:
- выбрать JavaScript (по умолчанию — TypeScript).
- выбрать имя каталога - tests
- добавить рабочий процесс GitHub Actions
- установить Playwright browsers
3. В package.json добавить команду yarn test:e2e  `yarn playwright test` 
4. Написать пробный тест https://playwright.dev/docs/writing-tests
 

Настройка Vitest: https://nextjs.org/docs/app/building-your-application/testing/vitest
1. Установить vitest `yarn add -D vitest @vitejs/plugin-react jsdom @testing-library/react`
2. Создать файл vitest.config.js
`import { defineConfig } from 'vitest/config'
import react from '@vitejs/plugin-react'
 
export default defineConfig({
  plugins: [react()],
  test: {
    environment: 'jsdom',
  },
})`

3. В  package.json добавить команду yarn test:unit
4. В  package.json добавить команду  "test": "playwright test && vitest"
5. Написать пробный тест

**Comment by foxprogs** [comment]
> 4\. Написать пробный тест https://playwright.dev/docs/writing-tests

тут я бы основывался на примере из документации некста

> 3\. В package.json добавить команду yarn test:unit

вот так должно быть

```
"scripts": {
  ...
  "test:unit": "vitest"
}
```

@DenisArger

**Comment by DenisArger** [comment]
> > 4. Написать пробный тест https://playwright.dev/docs/writing-tests
> 
> тут я бы основывался на примере из документации некста
> 
> > 3. В package.json добавить команду yarn test:unit
> 
> вот так должно быть
> 
> ```
> "scripts": {
>   ...
>   "test:unit": "vitest"
> }
> ```
> 
> @DenisArger

@foxprogs 
Понял, спасибо за уточнение. Буду действовать.
