### ISSUE TITLE
[Feature]: "Remember me" when user login

### ISSUE THREAD

**Issue by foxprogs** [glokascom/bibleVis#65]
### Task description:

При логине пользователь отмечает чекбокс `remember me` и сессия продляется автоматически, если пользователь заходит периодически на сайт

### Links to the layout:

[_No response_](https://www.figma.com/design/aAEsApaCTnTut2sSgLa6G3/BibleVis-GeCraft?node-id=2022-1180&t=hrYzj6DbELWbmZgt-4)

### Evaluation criteria:
1. Если не отмечать чекбокс то в течение какого-то времени пользователь разлогинивается.
2. Если отметить чекбокс, то каждый раз когла пользователь пользуется сайтом - его сессия продлевается.

### General solution:
Возможно такой функционал уже есть в документации к SB

**Comment by DenisArger** [comment]
Дополнительная информация:

- сеанс создается при входе пользователя в систему. По умолчанию он длится неопределенное время, и пользователь может иметь неограниченное количество активных сеансов на любом количестве устройств.  По умолчанию все сеансы активны до тех пор, пока пользователь не выйдет из системы или не выполнит какое-либо другое действие, завершающее сеанс. 

- для бесплатных аккаунтов  эти параметры изменить нельзя

- для платных:
Чтобы гарантировать, что пользователям необходимо периодически проходить повторную аутентификацию, вы можете установить положительное значение для  параметра «Пользовательские сеансы временного окна»  в  настройках аутентификации  вашего проекта. 

Чтобы гарантировать, что сеансы истекают после определенного периода бездействия, вы можете установить положительную продолжительность для  параметра «Тайм-аут бездействия»  в  настройках аутентификации  . 

Вы также можете принудительно установить только один активный сеанс для каждого пользователя на устройстве или браузере. Если эта опция включена, сеанс с момента последнего входа в систему останется активным, а остальные будут прекращены. Включите это с помощью  параметра «Один сеанс на пользователя»  в  настройках аутентификации  .


Источник: https://supabase.com/docs/guides/auth/sessions
