### ISSUE TITLE
[UI] Create Login/Register page

### ISSUE THREAD

**Issue by foxprogs** [glokascom/bibleVis#8]
### Task description:
Create Login/Register page with mobile version

### Links to the layout:
[Create Login/Register page](https://www.figma.com/design/aAEsApaCTnTut2sSgLa6G3/BibleVis-GeCraft?node-id=138-520&t=FyQyTlXc1ggUeswi-4)
____________________
### Evaluation criteria:
1. Modal
2. Sign Up Form.
3. Login Form
4. Success message

**Comment by Valyukhov** [comment]
@foxprogs так норм? user stories
