### ISSUE TITLE
[Feature]: Title and Description

### ISSUE THREAD

**Issue by foxprogs** [glokascom/bibleVis#89]
### Task description:

Надо продумать все тайтлы и дескрипшны для всех страниц на сайте

[Link to Google Doc](https://docs.google.com/spreadsheets/d/159isDzV8LJcYa5THN9i4o7gBMeLwjnit2lrofLG1AjE/edit?gid=0#gid=0)

### Evaluation criteria:
1.
2.

### Implementation steps:
1.
2.

**Comment by Valyukhov** [comment]
@foxprogs Это не совсем понятно.
Можешь уточнить задачу и время посчитать?

**Comment by foxprogs** [comment]
@savisky нужно продумать titile, description, social image для всех страниц
главная, логин, все статичные страницы, страница поиска, страница картинки, страница профиля
